Correctly recreate PVs after recycling
appuio/openshift-scripts pull request #6
Opened 2017-09-29 09:15 UTC by mhutter

When a PV had "special" attributes like annotations, labels or a storageclass configured, those attributes were lost during the recreation process.

This patch changes the behaviour of the gluster-recycle-pv script to not recreate each PV object, but instead only remove its `claimRef` attribute and the `bound-by-controller` annotation.

2017-09-29 11:03 UTC, hansmi requested changes

2017-09-29 11:03 UTC, hansmi commented on gluster-recycle-pv.sh
> +  oc annotate pv "$pv_name" pv.kubernetes.io/bound-by-controller-
This is not an atomic operation. You can patch out the annotation as well (set it to `null`, or use a [JSON patch](https://tools.ietf.org/html/rfc6902)).

2017-09-29 11:03 UTC, hansmi commented on gluster-recycle-pv.sh
> +  pv_path=$(oc get pv "$pv_name" -o template --template='{{.spec.glusterfs.path}}' 2>/dev/null)
I know this was in the code before, but there's no reason to hide errors. Drop the stderr redirection.

2017-09-29 11:03 UTC, hansmi commented on gluster-recycle-pv.sh
> +    echo "ERROR: Could not mount '${gluster_node_ip}:${pv_path}' to $temp_mount. Error code was $?. Aborting." >&2
Nitpick: `\"` instead of `'`.

2017-09-29 11:26 UTC, mhutter commented
@hansmi thanks, good catches! I've updated the PR accordingly

2017-09-29 11:39 UTC, hansmi requested changes

2017-09-29 11:39 UTC, hansmi commented on gluster-recycle-pv.sh
> +    echo "ERROR: Could not clean everything on '${pv_path}'. Aborting." >&2
`s/'/\\"/g` here too

2017-09-29 11:39 UTC, hansmi commented on gluster-recycle-pv.sh
> +  oc patch pv "$pv_name" -p '{"metadata":{"annotations":{"pv.kubernetes.io/bound-by-controller":null}},"spec":{"claimRef":null}}'
It's easier to read when wrapped and formatted:
```
oc patch pv "$pv_name" -p '{
  "metadata": {
    "annotations": {
      "pv.kubernetes.io/bound-by-controller": null
    }
  },
  "spec": {
    "claimRef": null
  }
}' 
```

2017-10-02 14:53 UTC, hansmi commented
LGTM

2017-10-02 15:14 UTC, merged